[webvtt]
base_url = "http://sample.ttml.server.com/ttml"

[api]
purge_header = "X-VIA-PURGE-KEY"
purge_key = "1r41jvbeledanudgou3ae8a2e9rkuplujkkm7uipetjq8uilehi6"

[util]
temp_dir = "/tmp/static-packager/temp"
upload_path_base_url = ""
local_path_base = "/tmp/static-packager/media"
script_dir = "/tmp/static-packager/scripts"
iframe_dir = "iframe"
disk = "/tmp/static-packager/media"
adaptor_path = "../../adaptors/"
check_for_unique_id = false

[downloader]
http_download = true
count = 2

[uploader]
count = 10

[workflow]
count = 10
stale_workflow_threshold = 14400000

[key-services]
base_url = "http://origin.keysvc-dev.mtvnservices.com"
private_base_path = "/api/private/key/create?acl="
public_base_path = "/get/encrypt.key?acl="
status_path = "/api/version"
security_key = "-----BEGIN RSA PRIVATE KEY-----\nMIIEpQIBAAKCAQEAhZSLbE8YyxnfoXSHV96ZTLp+nmIcyZwnYUVdcM3yd+xu4zal\nwrhTofoM55xC+5yxODCsSVYreC+pF9OdBFYqFGNtJSc0mQ+xOW2MyaFMbWttnrOU\naEyZ2HLzBytdgExpbTZ6OBSx6MoZOp/BZlcEepEW2TYkliaDMq/z2TPOyCIdmuPT\n0Pyw8Nahj7TlxrALiDlKpuBAZpHAX8W/o4duAZCI46UJaYFpL5xUhyuBisoJzSPb\nSysFqgTJyy+809A8vlQM87oVfYatN/Omaya6bo6sUTvAkQtruJhqb7et22Wxx5sc\nFi21xRMDOQaId4Bip/ZEY8fCzGkZkoZEPR6gpwIDAQABAoIBACRZmd8tXwfV0J81\nAKeOsZTJoy8ib8cFMUotABJ0WKj9s+cstcrZMhj/3IciZK/noeoyhI+oXUflYFRV\nh4Lol6bYr5jOpGeKd6WzA/7SX+PeugPXxmjjf3IBRdULnfQN1xqbGoMsToWUiW0E\nkDJzN4rK9LbDHw2lCUq/ytGuYXTgPk0w4PnN7lw6qnUEh8gYqLdUqi3XNpxXZa7x\nrLc60YmzOf0SO/okZFPQLM47YRGQfM6vV84XlaNziAmcrejIYLSuvsxAyDVM4zh4\n03BaaLB/B3xbj4QxLeea3JWBARBKp3R8mfrf3eDsPr6Fc34PrWTs5UTpC2vtQb6w\n9fvhOXECgYEA0fXIBsrfSmtdY6aTqc+lYAUX9Tv+z6wFZJtNLAscsy6kSdwuwWpw\nNFpJXRZCwqDGKpX1mx5yIbDwt44d3rZ7mooXizfMXDGgeHHqreyTOoCbeLAy8Ccb\noaG0qxdhlGmTkCBfkfJMcb9Qg75s6JdMSfQBJPFI+mn8PUiZxYVTMy0CgYEAot8k\nRIfPXdH4CmHWfiF3siTqXNE1fpKry3D+bHr/JTZ5s3DSVixdc4gAw2Kqr737SFTz\nMFXXswmgd3Nn8dhz/czGuGkqfp0aE4JAft2FC0VfovjenQcjaDy3pbswIz6bjxON\nNeo0kato/MiZpyzIaoP68rE/wuMXFQTW3gU8F6MCgYEAwNOmoj5dtj5GpceNpA41\nRqtG5o30JoxI464RwRpvgEycy8yxECeN5zboW9qe85quhNv2lkDu9uxHF30pB6q2\neCbNGqnjQOS/CP8uVg+I49jLcJr6HT79jIMzp1Iw5xnTUTG6NBLAjFL1Qhl4cmDJ\nyr2S83e522nNJAdyWkppL/0CgYEAnTciDhi+XUTZ1kO8xUHPBaHGrFOx/Hzd4eIv\nZU2Qzj34WfLUxiPLDUNB4VhzhHKxhY+is4yZSpRHViaLNpMG2/138Phq8Y76Zcx8\nLznrPAb6Gxl54T/LuMmrSAoZnFvJ0uE/lMR/fAFmtWN5ljqPNuoxKWVZM+j7Fen2\n8pdA+1sCgYEAtTe/DcLbP1ub6eujvtb2JlLdprlVkX+uuU2zVoWTBnDRe++/mv+T\nu2qDhaAT9FXDWnKyqzhMcQtZVcphUFod8zZUpPTT3CthcWCSx7s3Qd7OdFIOIkMf\n09Tdjwy3tN4IwbwdviH61tHq2l2QGSMq2UqoSinQ5s4duyGHExwy4q4=\n-----END RSA PRIVATE KEY-----"
issuer = "PkgSvc"
expiration = "600s"
algorithm = "RS512"
key_name = "encrypt_{id}.key"

[sqs]
sqs_aws_access_key_id = "AKIAJQWHTBOKV32UGAYQ"
sqs_aws_secret_access_key = "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"
sqs_aws_region = "us-east-1"
sqs_mock_enabled = false
sqs_queue_url = "https://sqs.us-east-1.amazonaws.com/470817450011/demo-queue"
sqs_poll_interval = 1000
sqs_default_message_visibility = 600

[database]

    [database.dynamodb]
    user = "AKIAJQWHTBOKV32UGAYQ"
    pass = "DnE52J2GiMYnrjdmbODPBw54Z7bTu3mItr0vhaQb"
    region = "us-east-1"
    use_local = true
    local_url = "http://dynamodb:8000"
    table_name = "StaticPackager"
    db_name = "staticpackager"
    use_auth = false
    authentication = ""
    replicaset_name = "test"
    replica_set = [""]
    auth_db = ""

    [database.mongodb]
    replica_set = [
        "dev01-packager-mdb01.us-east-1.aws.cloud.viacom.com:27017", 
        "dev02-packager-mdb01.us-east-1.aws.cloud.viacom.com:27017",
        "dev03-packager-mdb01.us-east-1.aws.cloud.viacom.com:27017"
    ]
    region = ""
    user = "packager0intglbw"
    pass = "fudraSwA3UJacE"
    table_name = "StaticPackager"
    db_name = "staticpackager"
    authentication = "SCRAM-SHA-1"
    replicaset_name = "test"
    auth_db = "admin"
    use_auth = false
    use_local = true
    local_url = "mongodb:27017"

[bucket]

    [bucket.netstorage]
    max_entries = 100
    hostname = "nonprodpackedorigin-nsu.akamaihd.net"
    keyname = "nonprod_packagedusr"
    key = "LalHuySgw5qYAaect8JqAy2kn65T6T53DqJ4i2N95T7UDenOE4"
    cpcode = "650265/dev"
    ssl = false
    status_check_namespace = "gsp.evergreenitem/stream_384x216_403052.m3u8"

[encoder]
encryption_mode = "AES-128"
segment_duration = 6
output_single_file = false
hls_version = 4
master_filename = "master"
iframe_filename = "iframe_{rendition}_{bitrate}.m3u8"
stream_level_filename = "stream_{rendition}_{bitrate}.m3u8"
ts_filename = "seg_{rendition}_{bitrate}_%d.ts"
binary_location = "/opt/bento4/bin"
initialization_vector = "random"
temp_iframe_mp4 = "tempVod_{workflowId}.mp4"